### ISSUE TITLE
Can you switch antenna with this driver?

### ISSUE THREAD

**Issue by andrewbradnan** [airspy/airspyhf#13]
I don't see any options with CubicSDR regarding VHF/UFH.  Not sure if that's a driver or host software problem.

thanks

**Comment by csete** [comment]
Not sure I understand what you want... the Airspy HF+ covers HF 9 kHz .. 31 MHz and VHF 60 .. 260 MHz but not UHF. This seems pretty consistent with one of the connectors being marked "H" and the other "V". They go into separate tuners (integrated in the chip) and to my knowledge there is no antenna switch in the hardware.
