### ISSUE TITLE
bandwidth in sdr# limited to a very small value

### ISSUE THREAD

**Issue by leim** [airspy/airspyhf#17]
I am using a airspy mini, conneted to a raspberry pi 3b+, running Spy Server v2.0.1629.

The raspberry pi 3b+ connected to my router with a 1000Mbps wired network.

My computer running Windows 10 64bit connected to my router with 5Ghz wifi.

I am running sdr#, connted to my spy server.

The available bandwidth is very limited, even not satisfied for listening to FM radio.

Below are my screenshots, notice the bandwidth in red circle, they are the max value i can toggle.

But when i connet my airspy mini directly to my computer usb port, they are not so limited.

I dont know why my airspy mini is acting like this when using spy server, i just wanna it to act as that it were connected directly to my usb port.

Please can anyone help me.

![1](https://user-images.githubusercontent.com/1665397/45372640-186ff800-b620-11e8-92a5-a3edde4e99d1.PNG)
![2](https://user-images.githubusercontent.com/1665397/45372641-19088e80-b620-11e8-9908-3aba8020d42d.PNG)
![3](https://user-images.githubusercontent.com/1665397/45372645-19088e80-b620-11e8-86b1-756d26da0aed.PNG)

Below is my spyserver.config file:

# SPY Server Configuration File
bind_host = 0.0.0.0
bind_port = 5555
maximum_clients = 10
allow_control = 1
maximum_bandwidth = 500000
fft_fps = 30
fft_bin_bits = 16
device_type = AirspyOne
device_serial = 0
initial_frequency = 99800000
frequency_correction_ppb = 0
initial_gain = 12
enable_bias_tee = 0
buffer_size_ms = 100
buffer_count = 20

**Comment by touil** [comment]
Use the mailing list for this kind of questions, not the bug tracker.
