### ISSUE TITLE
Source code for hfplus_ppb and hfplus_reboot missing

### ISSUE THREAD

**Issue by sdr1234** [airspy/airspyhf#18]
I can't update the firmware because I don't have a Windows computer.

**Comment by touil** [comment]
These tools are not open source.

**Comment by sdr1234** [comment]
@touil It is fine if there is some Windows specific code in there right now. Is that the reason why they are not? If this is not the reason why, then what is? How will Linux users update the firmware?

**Comment by touil** [comment]
Non-Windows users who want to flash => Return the unit to your retailer for flashing.

**Comment by Sevyls** [comment]
This comes as a surprise as the homepage stated:

Supported Operating Systems
Windows Vista, 7, 8, 8.1 and 10
Linux
*BSD
OSX
-- https://airspy.com/airspy-hf-plus/
Come on, you can't be serious in claiming it is a Windows only toolset for flashing an upgrade!

**Comment by touil** [comment]
Which is 100% accurate. Take any unit and it will operate nominally on any of these platforms.
Flashing is not a normally used functionality during the standard operation. It's not even described in the product specs. Furthermore, all firmwares are binary compatible with the hardware and the existing API.

If you think Windows stinks, then return your unit to the reseller. They will be more than happy to flash it for you.

**Comment by kholia** [comment]
Check out https://github.com/kholia/airspy-utils ;)

**Comment by touil** [comment]
And you think you are smart?

**Comment by soulnull** [comment]
I mean, he accomplished what you were too arrogant to do, so that probably answers your question.
