### ISSUE TITLE
Firmware Flash Tool is missing

### ISSUE THREAD

**Issue by Sevyls** [airspy/airspyhf#19]
A Tool to upgrade the device's firmware is missing for the Airspy HF+.
Please provide the sources how to flash this device.
A Linux binary is missing.

**Comment by touil** [comment]
Duplicate. https://github.com/airspy/airspyhf/issues/18

**Comment by kholia** [comment]
Check out https://github.com/kholia/airspy-utils ;)

**Comment by touil** [comment]
Third party flashing tools are not supported for obvious reasons. Customer support time, that is.
