### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by PA8E** [airspy/airspyhf#25]
When I try to compile airspyhf, I get the following error:
make
[ 25%] Linking CXX shared module libairspyhfSupport.so
/usr/bin/ld: CMakeFiles/airspyhfSupport.dir/Settings.cpp.o:(.data.rel.ro._ZTV13SoapyAirspyHF[_ZTV13SoapyAirspyHF]+0x148): undefined reference to `SoapySDR::Device::hasIQBalanceMode(int, unsigned long) const'
/usr/bin/ld: CMakeFiles/airspyhfSupport.dir/Settings.cpp.o:(.data.rel.ro._ZTV13SoapyAirspyHF[_ZTV13SoapyAirspyHF]+0x150): undefined reference to `SoapySDR::Device::setIQBalanceMode(int, unsigned long, bool)'
/usr/bin/ld: CMakeFiles/airspyhfSupport.dir/Settings.cpp.o:(.data.rel.ro._ZTV13SoapyAirspyHF[_ZTV13SoapyAirspyHF]+0x158): undefined reference to `SoapySDR::Device::getIQBalanceMode(int, unsigned long) const'
/usr/bin/ld: CMakeFiles/airspyhfSupport.dir/Streaming.cpp.o: in function `SoapyAirspyHF::getStreamFormats[abi:cxx11](int, unsigned long) const':
Streaming.cpp:(.text+0x777): undefined reference to `SoapySDR::ConverterRegistry::listTargetFormats(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/airspyhfSupport.dir/Streaming.cpp.o: in function `SoapyAirspyHF::setupStream(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)':
Streaming.cpp:(.text+0xc35): undefined reference to `SoapySDR::ConverterRegistry::listSourceFormats(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: Streaming.cpp:(.text+0xc94): undefined reference to `SoapySDR::ConverterRegistry::getFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SoapySDR::ConverterRegistry::FunctionPriority const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/airspyhfSupport.dir/build.make:116: libairspyhfSupport.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/airspyhfSupport.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Ubuntu 19.10, Linux 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by touil** [comment]
This is unrelated to our code.
