### ISSUE TITLE
HF+ Discover compatibility on Raspberry Pi OS (model 4B)

### ISSUE THREAD

**Issue by LeoFurr** [airspy/airspyhf#27]
Trying to set up the Spyserver on raspberry pi, however; it appears that the system doesn’t recognise the Airpsy discovery with those drivers. 

Curious if this is some compatibility issue or some other case? 

Tried various config settings ranging from detection modes to serial numbers, the result is “server busy” response on SDR#. 

Clues?

**Comment by touil** [comment]
Please use the mailing list for discussions. This area is reserved to developers.
