### ISSUE TITLE
FT8 decoding (airspyhf_rx vs rtl_sdr)

### ISSUE THREAD

**Issue by kholia** [airspy/airspyhf#29]
FT8 decoding works well with RTL-SDR V3 Dongle:

```
$ ~/librtlsdr/src/rtl_sdr -s 1000000 -f 14074000 -g 20 -O dm=4:dm=20E6 - | csdr convert_u8_f | csdr fir_decimate_cc 250 0.00166665 HAMMING > /tmp/ft8_14074000.c2

$ ./ft8d backup/ft8_14074000.c2 
 00   2.6  -9 -0.15 14074124 VU3CER VU3FOE MK68   MK68
 00   3.8  -6 -0.15 14074424 VU3CER VU3FOE MK68   MK68
 00   3.1  -5 -0.15 14074523 VU3CER VU3FOE MK68   MK68
 00   3.3   3 -0.14 14074623 VU3CER VU3FOE MK68   MK68
 00   3.8  12 -0.13 14074723 VU3CER VU3FOE MK68   MK68
```

The `ft8d` binary comes from https://github.com/pavel-demin/ft8d project.

Next, I tried using Airspy HF+ Discovery instead of the RTL-SDR V3 Dongle.

```
$ airspyhf_rx -r /dev/stdout -a 384000 -f 14.074000 -g on -m on - | csdr fir_decimate_cc 80 0.00166665 HAMMING > /tmp/ft8_14074000.c2"

$ ./ft8d backup/ft8_14074000.c2
<no decodes>
```

https://github.com/airspy/airspyhf/blob/master/tools/src/airspyhf_rx.c <-- I am using this to grab the IQ samples. I am guessing that the output format is CF32 which is directly supported by `csdr` tools. I could be totally wrong here.

No luck here!

Next, I tried using the Airspy HF+ Discover with `rx_tools`.

```
$ rx_sdr -s 384000 -f 14074000 -I CF32 -F CF32 - | csdr fir_decimate_cc 80 0.00166665 HAMMING > /tmp/ft8_14074000.c2

$ ./ft8d backup/ft8_14074000.c2
<no decodes>
```

No luck here either.

To ensure that FT8 traffic in always on the air, I use my https://github.com/kholia/Easy-Digital-Beacons-v1 project to generate such test FT8 traffic.

I am trying to understand where the bug is. Am I using `csdr` correctly? Or is airspyhf_rx subtly different in its behavior compared to rtl_sdr?

Note: All software versions are freshly built from git repos.

![Screenshot_2021-10-31_18-56-39](https://user-images.githubusercontent.com/79528/139590875-ba3499b6-2785-4223-83a9-c3213bdc1127.png)

When airspyhf_rx is operated in .wav mode (-w flag), I can play and decode the resultant .wav files just fine. So, what could be subtly different in the stdout mode?

Sample files:

[rtl_sdr_internal_antenna_14074000.c2.txt](https://github.com/airspy/airspyhf/files/7449139/rtl_sdr_internal_antenna_14074000.c2.txt) - Recorded via RTL-SDR.

This IQ file can be opened in `inspectrum` software.

![Proper RTL-SDR @ 4800 - Screenshot_2021-10-31_20-38-16](https://user-images.githubusercontent.com/79528/139591034-efeba576-2bd1-4d30-b2ea-bb6e7d3c3908.png)

The FSK signal is clearly visible in the RTL-SDR recording.

[hello_14074000.c2.txt](https://github.com/airspy/airspyhf/files/7449143/hello_14074000.c2.txt) - Recorded via Airspy HF+ Discovery.

![Screenshot_2021-10-31_21-05-40](https://user-images.githubusercontent.com/79528/139591134-37ea065e-8ce8-4c41-8613-18263378dde7.png)

The signal looks like FSK too but doesn't decode. The timing (needed for decoding FT8 signals) seems to be quite fine.

What could be my next debugging steps to determine how airspyhf_rx is different from rtl_sdr? Thanks for the help.

**Comment by touil** [comment]
This is a software issue and unrelated to the firmware and user library. Use the mailing list to get familiar with this matter: https://groups.io/g/airspy/messages
