### ISSUE TITLE
Callback never called

### ISSUE THREAD

**Issue by srcejon** [airspy/airspyhf#42]
SDRangel successfully uses this library on Windows + recent versions of Linux, but it doesn't appear to work on MacOS (and in the past there were some reports of it not working on some Linux distributions with USB 3 ports, but OK when forced to USB 2). Functions to set the frequency and sample rate seem OK, but the callback never appears to be called.

It seems that the example airspyhf_rx program doesn't work on MacOS with the same symptoms (Tested using Big Sur using libusb 1.0.26 and 1.0.23), although some say other SDR software can run OK.

Any idea what the problem might be or how to debug? Thanks

**Comment by srcejon** [comment]
Also, trying to run airspyhf_rx for a second time, results in:

    airspyhf_open() failed.

And then you need to unplug the Airspy and plug it back in again.

**Comment by touil** [comment]
These problems are unrelated to libairspyhf. Check your kernel and libusb.

**Comment by srcejon** [comment]
As said, I've tried two versions of libsub (1.0.26 and 1.0.23) - which version do you recommend?

Which kernel should be used on MacOS?

**Comment by touil** [comment]
To be more precise: This is a problem with your system, not our code. Any version of libusb >= 1.0.19 should work, unless it broke the compatibility with your system. As this is still outside our code, you will have to figure it out on your own.
