### ISSUE TITLE
What does this repo actually do? It's not clear

### ISSUE THREAD

**Issue by anthonybudd** [airspy/airspyhf#45]
I am aware this is a driver for AirSpy SDR devices but it's not entirely clear what this repo does or how to use it.

The first line reads:
> This repository contains host software (Linux/Windows) for Airspy HF+, a high performance software defined radio for the HF and VHF bands.

Ok, that's all well and good but there's no additional information about how to actually use this project once you've compiled it.

I have also looked at this page https://airspy.com/airspy-hf-plus (link found in readme) and again there's multiple paragraphs about all of the amazing things this library can do but NOTHING about how to actually use it. Also the word "docs" or "documentation" does not exist on this repo or the AirSpy website.

Question: How do I use this repo?

**Comment by touil** [comment]
Don't abuse the issue tracker to ask harvest the developers time. Use this tool after:
1) Understanding what a user mode driver is;
2) Have done some useful code on your own based on your own understanding;
3) Found a legitimate reason to question the validity of the code in this repo.

You are now in step 0, which can be answered in the mailing list: https://groups.io/g/airspy/messages

**Comment by anthonybudd** [comment]
Or just write better ReadMe's so devs can actually use your project...

_You're the problem here._

**Comment by touil** [comment]
This project is not intended for "developers."

**Comment by anthonybudd** [comment]
Again, _You're the problem here._

IDK if you know this but this site is pretty popular with developers.

**Comment by touil** [comment]
"PHP & Node Expert"...

**Comment by anthonybudd** [comment]
Point proven, you read my ReadMe and you know exactly what I do and what I'm about. 

That's what ReadMe's are for 😉

**Comment by touil** [comment]
I suggest you try [this repo](https://github.com/e10v/dunning-kruger) first.

**Comment by anthonybudd** [comment]
Me: "How do I use this repo?"
You: e10v/dunning-kruger

3rd time's a charm.... _You're the problem here._
