### ISSUE TITLE
airspyhf_set_user_output purpose

### ISSUE THREAD

**Issue by amontefusco** [airspy/airspyhf#6]
Not really an issue, just a help request.
What is the function

int ADDCALL airspyhf_set_user_output(airspyhf_device_t* device, airspyhf_user_output_t pin, airspyhf_user_output_state_t value)

meant to do ?
Do I should expect an airspyhf_**get**_user_output in the near future ?
Asking just to know if it is worth to implement into the Extio dll.

**Comment by touil** [comment]
This function sets the state of the GPIO pins. In fact, these pins can only be outputs for the moment.
